# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test:unit
      - run: yarn codecov
      - run:
          name: Generate Release Commits for sentry
          command: |
            curl https://sentry.io/api/hooks/release/builtin/1241250/$SENTRY_HOOK_ID/ \
            -X POST \
            -H 'Content-Type: application/json' \
            -d "{\"version\": \"$CIRCLE_SHA1\"}"
      - run:
          name: Send commits to Sentry
          command: yarn sentry-cli releases set-commits --auto $CIRCLE_SHA1
